# Configuración de la API-Gateway de EyesFood implementada con express-gateway https://www.express-gateway.io/docs/
# http contiene el puerto donde la API-Gateway escucha las requests
http:
  port: ${PORT}
  hostname: "0.0.0.0"
admin:
  port: ${ADMIN_PORT}
  host: "0.0.0.0"
# apiEndopoints contiene los paths asociados a cada microservicio.
# serviceEndpoints contiene la url donde se encuentra cada microservicio
apiEndpoints:
  login: 
    host: "*"
    paths: ["/auth/*", "/auth/*/*", "/activate/*"]
  ms-accounts:
    host: "*"
    paths: ["/users", "/users/*", "/experts", "/experts/*", "/stores", "/stores/*",
             "/roles", "/roles/*", "/permissions", "/permissions/*"]
  ms-food-profile:
    host: "*"
    paths: ["/food", "/food/*", "/search", "/search/*"]
  ms-food-edits:
    host: "*"
    paths: ["/submissions", "/submissions/*", "submissions/*/*", "/submissions-food", "/submissions-food/*", 
            "/submissions-additives", "/submissions-additives/*", "/submissions-allergens", "/submissions-allergens/*",
            "/submissions-images"]
  ms-user-profile:
    host: "*"
    paths: ["/profile", "/profile/*", "/profile/*/*"]
  ms-food-diary:
    host: "*"
    paths: ["/food-diary", "/food-diary/*", "/food-diary-google/*", "/diary-entry-google/*"]
  ms-comments:
    host: "*"
    paths: ["/comments-expert/*", "/comments-store/*", "/comments-expert", "/comments-store", "/comments-food", "/comments-food/*"]
  ms-experts:
    host: "*"
    paths: ["/articles", "/articles/*", "/food-advice", "/food-advice/*", "/expert-profile", "/expert-profile/*"]
  ms-stores:
    host: "*"
    paths: ["/catalogue", "/catalogue/*", "/store-profile", "/store-profile/*"]
  ms-notification:
    host: "*"
    paths: ["/notification", "/notification/*", "/userhasnotification", "/userhasnotification/*"]
  ms-stats:
    host: "*"
    paths: ["/stats", "/stats/*", "/users-stats", "/users-stats/*"]
serviceEndpoints:
  login:
    url: "http://ms-accounts:2000"  # Replace with correct service name and port if needed
  ms-accounts:
    url: "http://ms-accounts:2000"
  ms-comments:
    url: "http://ms-comments:2001"
  ms-experts:
    url: "http://ms-experts:2002"
  ms-food-diary:
    url: "http://ms-food-diary:2003"
  ms-food-edits:
    url: "http://ms-food-edits:2004"
  ms-food-profile:
    url: "http://ms-food-profile:2005"
  ms-notification:
    url: "http://ms-notification:2006"
  ms-stats:
    url: "http://ms-stats:2007"
  ms-stores:
    url: "http://ms-stores:2008"
  ms-user-profile:
    url: "http://ms-user-profile:2009"

# policies contiene funcionalidades que pueden ser utilizadas para evaluar requests y realizar acciones sobre ellas
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - jwt
  - rate-limit
  - request-transformer
pipelines:
  login:
    apiEndpoints:
      - login
    policies:
    # cors es necesario para manejar la autenticación y autorización de usuarios a traves de jsonwebtoken
      - cors:
          - action:
              origin: true
              credentials: true
              methods: 'HEAD,PUT,PATCH,POST,DELETE,GET'
              exposedHeaders : ['allowed-custom-header']
              allowedHeaders :  ['content-type', 'Authorization', "Access-Control-Allow-Origin", "cookies", "set-cookies"]
              preflightContinue : false
              optionsSuccessStatus  : 204
      - proxy:
          - action:
              serviceEndpoint: login
              changeOrigin: true

  ms-accounts:
    apiEndpoints:
      - ms-accounts
    policies:
      - cors:
            - action:
                origin: true
                credentials: true
                methods: 'HEAD,PUT,PATCH,POST,DELETE,GET'
                exposedHeaders : ['allowed-custom-header']
                allowedHeaders :  ['content-type', 'Authorization', "Access-Control-Allow-Origin", "cookies", "set-cookies"]
                preflightContinue : false
                optionsSuccessStatus  : 204
    # jwt revisa que la jsonwebtoken que viene en el header "Authorization" de la request sea válida
    # secretOrPublicKey debe ser igual a la utilizada en el microservicio para crear la token
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              checkCredentialExistence: false

      - proxy:
          - action:
              serviceEndpoint: ms-accounts
              changeOrigin: true

  ms-food-profile:
    apiEndpoints:
      - ms-food-profile
    policies:
      - cors:
            - action:
                origin: true
                credentials: true
                methods: 'HEAD,PUT,PATCH,POST,DELETE,GET'
                exposedHeaders : ['allowed-custom-header']
                allowedHeaders :  ['content-type', 'Authorization', "Access-Control-Allow-Origin", "cookies", "set-cookies"]
                preflightContinue : false
                optionsSuccessStatus  : 204
    # jwt revisa que la jsonwebtoken que viene en el header "Authorization" de la request sea válida
    # secretOrPublicKey debe ser igual a la utilizada en el microservicio para crear la token
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              checkCredentialExistence: false

      - proxy:
          - action:
              serviceEndpoint: ms-food-profile
              changeOrigin: true

  ms-food-edits:
    apiEndpoints:
      - ms-food-edits
    policies:
      - cors:
            - action:
                origin: true
                credentials: true
                methods: 'HEAD,PUT,PATCH,POST,DELETE,GET'
                exposedHeaders : ['allowed-custom-header']
                allowedHeaders :  ['content-type', 'Authorization', "Access-Control-Allow-Origin", "cookies", "set-cookies"]
                preflightContinue : false
                optionsSuccessStatus  : 204
    # jwt revisa que la jsonwebtoken que viene en el header "Authorization" de la request sea válida
    # secretOrPublicKey debe ser igual a la utilizada en el microservicio para crear la token
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              checkCredentialExistence: false
      # - request-transformer:
      #     - action:
      #         body:
      #             add:
      #                 user: req.user

      - proxy:
          - action:
              serviceEndpoint: ms-food-edits
              changeOrigin: true
  ms-user-profile:
    apiEndpoints:
      - ms-user-profile
    policies:
      - cors:
            - action:
                origin: true
                credentials: true
                methods: 'HEAD,PUT,PATCH,POST,DELETE,GET'
                exposedHeaders : ['allowed-custom-header']
                allowedHeaders :  ['content-type', 'Authorization', "Access-Control-Allow-Origin", "cookies", "set-cookies"]
                preflightContinue : false
                optionsSuccessStatus  : 204
    # jwt revisa que la jsonwebtoken que viene en el header "Authorization" de la request sea válida
    # secretOrPublicKey debe ser igual a la utilizada en el microservicio para crear la token
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              checkCredentialExistence: false

      - proxy:
          - action:
              serviceEndpoint: ms-user-profile
              changeOrigin: true
  ms-comments:
    apiEndpoints:
      - ms-comments
    policies:
      - cors:
            - action:
                origin: true
                credentials: true
                methods: 'HEAD,PUT,PATCH,POST,DELETE,GET'
                exposedHeaders : ['allowed-custom-header']
                allowedHeaders :  ['content-type', 'Authorization', "Access-Control-Allow-Origin", "cookies", "set-cookies"]
                preflightContinue : false
                optionsSuccessStatus  : 204
    # jwt revisa que la jsonwebtoken que viene en el header "Authorization" de la request sea válida
    # secretOrPublicKey debe ser igual a la utilizada en el microservicio para crear la token
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              checkCredentialExistence: false

      - proxy:
          - action:
              serviceEndpoint: ms-comments
              changeOrigin: true
  ms-food-diary:
    apiEndpoints:
      - ms-food-diary
    policies:
      - cors:
            - action:
                origin: true
                credentials: true
                methods: 'HEAD,PUT,PATCH,POST,DELETE,GET'
                exposedHeaders : ['allowed-custom-header']
                allowedHeaders :  ['content-type', 'Authorization', "Access-Control-Allow-Origin", "cookies", "set-cookies"]
                preflightContinue : false
                optionsSuccessStatus  : 204
    # jwt revisa que la jsonwebtoken que viene en el header "Authorization" de la request sea válida
    # secretOrPublicKey debe ser igual a la utilizada en el microservicio para crear la token
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              checkCredentialExistence: false

      - proxy:
          - action:
              serviceEndpoint: ms-food-diary
              changeOrigin: true
  ms-experts:
    apiEndpoints:
      - ms-experts
    policies:
      - cors:
            - action:
                origin: true
                credentials: true
                methods: 'HEAD,PUT,PATCH,POST,DELETE,GET'
                exposedHeaders : ['allowed-custom-header']
                allowedHeaders :  ['content-type', 'Authorization', "Access-Control-Allow-Origin", "cookies", "set-cookies"]
                preflightContinue : false
                optionsSuccessStatus  : 204
    # jwt revisa que la jsonwebtoken que viene en el header "Authorization" de la request sea válida
    # secretOrPublicKey debe ser igual a la utilizada en el microservicio para crear la token
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              checkCredentialExistence: false

      - proxy:
          - action:
              serviceEndpoint: ms-experts
              changeOrigin: true

  ms-stores:
    apiEndpoints:
      - ms-stores
    policies:
      - cors:
            - action:
                origin: true
                credentials: true
                methods: 'HEAD,PUT,PATCH,POST,DELETE,GET'
                exposedHeaders : ['allowed-custom-header']
                allowedHeaders :  ['content-type', 'Authorization', "Access-Control-Allow-Origin", "cookies", "set-cookies"]
                preflightContinue : false
                optionsSuccessStatus  : 204
    # jwt revisa que la jsonwebtoken que viene en el header "Authorization" de la request sea válida
    # secretOrPublicKey debe ser igual a la utilizada en el microservicio para crear la token
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              checkCredentialExistence: false

      - proxy:
          - action:
              serviceEndpoint: ms-stores
              changeOrigin: true

  ms-notification:
    apiEndpoints:
      - ms-notification
    policies:
      - cors:
            - action:
                origin: true
                credentials: true
                methods: 'HEAD,PUT,PATCH,POST,DELETE,GET'
                exposedHeaders : ['allowed-custom-header']
                allowedHeaders :  ['content-type', 'Authorization', "Access-Control-Allow-Origin", "cookies", "set-cookies"]
                preflightContinue : false
                optionsSuccessStatus  : 204
    # jwt revisa que la jsonwebtoken que viene en el header "Authorization" de la request sea válida
    # secretOrPublicKey debe ser igual a la utilizada en el microservicio para crear la token
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              checkCredentialExistence: false

      - proxy:
          - action:
              serviceEndpoint: ms-notification
              changeOrigin: true

  ms-stats:
    apiEndpoints:
      - ms-stats
    policies:
      - cors:
            - action:
                origin: true
                credentials: true
                methods: 'HEAD,PUT,PATCH,POST,DELETE,GET'
                exposedHeaders : ['allowed-custom-header']
                allowedHeaders :  ['content-type', 'Authorization', "Access-Control-Allow-Origin", "cookies", "set-cookies"]
                preflightContinue : false
                optionsSuccessStatus  : 204
    # jwt revisa que la jsonwebtoken que viene en el header "Authorization" de la request sea válida
    # secretOrPublicKey debe ser igual a la utilizada en el microservicio para crear la token
      - jwt:
          - action:
              secretOrPublicKey: ${JWT_SECRET}
              checkCredentialExistence: false

      - proxy:
          - action:
              serviceEndpoint: ms-stats
              changeOrigin: true
